//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaTest.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string country { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Code { get; set; }
    
        public virtual category category { get; set; }
    }
}
